# Generated by Django 5.1.3 on 2024-12-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('session_id', models.UUIDField(primary_key=True, serialize=False)),
                ('player_stack', models.IntegerField(default=200)),
                ('bot_stack', models.IntegerField(default=200)),
                ('current_street', models.CharField(max_length=20)),
                ('pot', models.IntegerField(default=0)),
                ('player_cards', models.JSONField(default=list)),
                ('board_cards', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'game_sessions',
            },
        ),
    ]
