# Generated by Django 5.1.3 on 2024-12-23 00:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='deck_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
