# Generated by Django 5.1.3 on 2024-12-25 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('player_stack', models.IntegerField(default=0)),
                ('bot_stack', models.IntegerField(default=0)),
                ('current_street', models.CharField(max_length=20)),
                ('pot', models.IntegerField(default=0)),
                ('player_cards', models.JSONField(default=list)),
                ('board_cards', models.JSONField(default=list)),
                ('deck_state', models.JSONField(default=dict)),
                ('game_state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_sessions',
            },
        ),
    ]
