# Generated by Django 5.1.3 on 2024-12-25 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_alter_gamesession_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='user',
        ),
    ]
