# Generated by Django 5.1.4 on 2024-12-30 21:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0005_usercode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='hands_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='hands_to_play',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player_initial_stack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player_max_rebuys',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AvailableGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('game_type', models.CharField(choices=[('coins', 'Coins'), ('gems', 'Gems')], max_length=5)),
                ('total_hands', models.IntegerField()),
                ('remaining_hands', models.IntegerField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('initial_stack', models.IntegerField()),
                ('max_rebuys', models.IntegerField()),
                ('bot_code', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'available_games',
                'ordering': ['-posted_on'],
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='available_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poker.availablegame'),
        ),
    ]
