# Generated by Django 5.1.4 on 2024-12-30 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0006_gamesession_hands_played_gamesession_hands_to_play_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablegame',
            name='bot_code',
        ),
        migrations.AddField(
            model_name='availablegame',
            name='bot_name',
            field=models.CharField(default='ReBeL_test', max_length=50),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='play_mode',
            field=models.CharField(choices=[('human', 'Human vs Bot'), ('bot', 'Bot vs Bot')], default='human', max_length=5),
        ),
        migrations.CreateModel(
            name='BotRepository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bot_repository',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='availablegame',
            name='bot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='poker.botrepository'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='opponent_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_sessions', to='poker.botrepository'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_sessions', to='poker.botrepository'),
        ),
        migrations.AddConstraint(
            model_name='botrepository',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_bot_name_per_user'),
        ),
    ]
