# Generated by Django 5.1.4 on 2024-12-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_github_link_customuser_linkedin_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_gems_earned',
            field=models.BigIntegerField(default=0),
        ),
    ]
