# Generated by Django 5.1.4 on 2024-12-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_total_gems_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new_password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_change_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_change_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
